data:
  train_dir: "datasets/panasia/train/images"
  train_ann: "datasets/panasia/train/train_annotations.csv"
  val_dir: "datasets/panasia/test/images"
  val_ann: "datasets/panasia/test/test_annotations.csv"
  batch_size: 4
  num_workers: 8

model:
  config_path: "groundingdino/config/GroundingDINO_SwinT_OGC.py"
  weights_path: "weights/groundingdino_swint_ogc.pth"

training:
  num_epochs: 10
  learning_rate: 1e-3
  save_dir: "weights/panasia"
  save_frequency: 5
  warmup_epochs: 5
  use_lora: true
  visualization_frequency: 5